tasks:
  - init: docker-compose build
    command: chown :13337 -R ./hasura && chmod 775 ./hasura && chmod g+s ./hasura && docker-compose -f docker-compose.gitpod.yml up -d

ports:
  ## Hasura Instance
  - port: 8080
    visibility: public
  ## CLI API
  - port: 9693
    visibility: public
  ## CLI Console
  - port: 9695
    onOpen: open-browser
