version: '3.6'
services:

  ## Default Hasura Setup ##
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.3.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"generateasecurepasswordforyourjwtkey", "issuer":"hasura-auth"}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_DEV_MODE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "apt-get update -y && apt-get install -y curl && curl --fail http://localhost:8080/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  ## CLI Deployment Example ##
  cli:
    build: ../../cli
    depends_on:
      hasura:
        condition: service_healthy
    volumes:
      - ./hasura:/usr/src/hasura
      - ./migrate.sh:/usr/src/migrate.sh
    command: bash -c "/usr/src/migrate.sh"
    environment:
      HASURA_URL: host.docker.internal:8080
      HASURA_PROTOCOL: HTTP://
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret