version: 3
endpoint: http://localhost:8080
admin_secret: myadminsecret
metadata_directory: metadata
HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/database
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:5000
